version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
    run: gradle clean
    run: gradle build  

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build