version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
        name: Gradle Clean
        command: gradle clean
      - run:
        name: Gradle build
        command: gradle build  
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build